### ISSUE TITLE
[Bug] Incompatibility with Simple Hats Fabric

### ISSUE THREAD

**Issue by PalgamingHD** [wisp-forest/accessories#39]
None of the hat slots work with the simple hats + trinkets compat

**Comment by Dragon-Seeker** [comment]
It seems to be down to the method in which they add the ability to equip the hats as they [mixin directly](https://github.com/fonnymunkey/SimpleHats/blob/cd62f97e3da623d12651396953bca0db0a04b6c1/src/main/java/fonnymunkey/simplehats/mixin/core/MixinTrinketsApi.java#L20) within the trinkets API instead of using a custom predicate or using the tag method built into the slot.

**Comment by Dragon-Seeker** [comment]
Sent PR's to get such fixed
