### ISSUE TITLE
[1.20.1] Incompatibility with More Banner Features

### ISSUE THREAD

**Issue by Scuber2007** [wisp-forest/accessories#56]
![image](https://github.com/user-attachments/assets/68a854a4-be95-40dc-9127-5f8e64fae915)
![image](https://github.com/user-attachments/assets/dbee5eff-a3fc-4274-8d0b-2629be97e087)

**Comment by Dragon-Seeker** [comment]
The reason for this not working is due to the developer has bypassed the API call to ask if a Mod is provided which will not find the provided id of trinkets from the compat layer leading to such not fully working: https://github.com/KxmischesDomi/MoreBannerFeatures/blob/2144c5912bc14959a627bd8696cf0c233acdfd15/src/main/java/de/kxmischesdomi/morebannerfeatures/MoreBannerFeatures.java#L24C1-L24C158

**Comment by Dragon-Seeker** [comment]
They are bypassing the API within FabricLoader for checking mod info leading to this issue being more on there side than mine in this case.

**Comment by Dragon-Seeker** [comment]
Fundamentally this is a problem fixable on the side of the given mod author to use the platforms loader method rather than scanning the mod containers meaning such an Issue should be made on their github for them to deal with.
