### ISSUE TITLE
[Crash] Ticking player

### ISSUE THREAD

**Issue by JellyBubb1e** [wisp-forest/accessories#63]
https://mclo.gs/L5c6qnf
https://mclo.gs/uLLCDRu

**Comment by JellyBubb1e** [comment]
The related mod is Sophisticated Backpacks.

**Comment by Dragon-Seeker** [comment]
Can confirm such to exist with latest release of 1.20.1... I am getting annoyed with how Minecraft is with strict checks for things that do not matter at all with NBT but will investigate a solution to this issues.

**Comment by Dragon-Seeker** [comment]
Have a working fix for such an issue. Seems that this also has the possibility of happening within 1.21 version just unlikely due to the nonexisting reliance on UUID for modifers

**Comment by Dragon-Seeker** [comment]
Ok, such has been uploaded to Curseforge and Modrinth which seems to only impact the 1.20.1 version. 

Will need to figure out why as the fix should be required for 1.21 but I have a clue why such is working due to DFU bug actually but glad for it this time as it doesn't seem to hurt me this time. Closing this as solved for now.
