### ISSUE TITLE
[BUG] [1.20.1-FORGE] Tool Belt not Working

### ISSUE THREAD

**Issue by TeQTabanca** [wisp-forest/accessories#96]
### 1- The buttons in the InventoryProfilesNext mode are interconnected. Finally, if I turn on the accessory button with the item and press one of the buttons in the InventoryProfilesNext mode, there will be 2 of the items I bought, but if I turn on the accessory mode again or try to throw them on the ground, 2 items will disappear.

Video:

https://github.com/user-attachments/assets/98612a63-fb1d-4ee1-bf02-20bd2a523d7c

### 2- Doesn't work properly with Tool Belt mode

https://github.com/user-attachments/assets/4a8eb209-9ded-4365-b67b-a77f27743e14

**Comment by Dragon-Seeker** [comment]
1. This seems more like an IPN issue or an issue within the modpack itself so frankly not much I can do as it would require. It's just a client desync of some time for the slot and it's nothing to worry heavily about.
2. Will investigate such further.

Next time you submit an issue, please submit issues separately for each mod rather than grouping them under one issue on Github.
